<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class GreensandJsh extends Model
{


    protected $table = 'tb_greensand_check_jsh';

    protected $fillable = [
        'date',
        'shift',
        'mm',
        'mix_ke',
        'mix_start',
        'mix_finish',
        'mm_p',
        'mm_c',
        'mm_gt',
        'mm_cb_mm',
        'mm_cb_lab',
        'mm_m',
        'machine_no',
        'mm_bakunetsu',
        'mm_ac',
        'mm_tc',
        'mm_vsd',
        'mm_ig',
        'mm_cb_weight',
        'mm_tp50_weight',
        'mm_tp50_height',
        'mm_ssi',
        'add_m3',
        'add_vsd',
        'add_sc',
        'bc12_cb',
        'bc12_m',
        'bc11_ac',
        'bc11_vsd',
        'bc16_cb',
        'bc16_m',
        'rs_time',
        'rs_type',
        'bc9_moist',
        'bc10_moist',
        'bc11_moist',
        'bc9_temp',
        'bc10_temp',
        'bc11_temp',
        'add_water_mm',
        'add_water_mm_2',
        'temp_sand_mm_1',
        'temp_sand_mm_2',
        'total_air_mm1',
        'total_air_mm2',
        'total_mixing_mm1',
        'total_mixing_mm2',
        'total_air_bc9',
        'total_flask',
        'rcs_pick_up',
        'rcs_avg',
        'add_bentonite_ma',
        'total_sand',
        'add_water_bc10',
        'lama_bc10_jalan',
        'rating_pasir_es',
        'bc9_ic_moist',
        'bc9_ic_ac',
        'ssi1_awal',
        'ssi1_akhir',
        'ssi2_awal',
        'ssi2_akhir',
        'created_log',
        'updated_log',
    ];

    protected $casts = [
        'date' => 'datetime',
        'mix_ke' => 'integer',
        'mix_start' => 'string',
        'mix_finish' => 'string',
        'rs_time' => 'string',
        'machine_no' => 'string',
        'mm_p' => 'decimal:2',
        'mm_c' => 'decimal:2',
        'mm_gt' => 'decimal:2',
        'mm_cb_mm' => 'decimal:2',
        'mm_cb_lab' => 'decimal:2',
        'mm_m' => 'decimal:2',
        'mm_bakunetsu' => 'decimal:2',
        'mm_ac' => 'decimal:2',
        'mm_tc' => 'decimal:2',
        'mm_vsd' => 'decimal:2',
        'mm_ig' => 'decimal:2',
        'mm_cb_weight' => 'decimal:2',
        'mm_tp50_weight' => 'decimal:2',
        'mm_tp50_height' => 'decimal:2',
        'mm_ssi' => 'decimal:2',
        'add_m3' => 'decimal:2',
        'add_vsd' => 'decimal:2',
        'add_sc' => 'decimal:2',
        'bc12_cb' => 'decimal:2',
        'bc12_m' => 'decimal:2',
        'bc11_ac' => 'decimal:2',
        'bc11_vsd' => 'decimal:2',
        'bc16_cb' => 'decimal:2',
        'bc16_m' => 'decimal:2',
        'bc9_moist' => 'decimal:2',
        'bc10_moist' => 'decimal:2',
        'bc11_moist' => 'decimal:2',
        'bc9_temp' => 'decimal:2',
        'bc10_temp' => 'decimal:2',
        'bc11_temp' => 'decimal:2',
        'add_water_mm' => 'decimal:2',
        'add_water_mm_2' => 'decimal:2',
        'temp_sand_mm_1' => 'decimal:2',
        'temp_sand_mm_2' => 'decimal:2',
        'total_air_mm1' => 'decimal:2',
        'total_air_mm2' => 'decimal:2',
        'total_mixing_mm1' => 'decimal:2',
        'total_mixing_mm2' => 'decimal:2',
        'total_air_bc9' => 'decimal:2',
        'total_flask' => 'decimal:2',
        'rcs_pick_up' => 'decimal:2',
        'rcs_avg' => 'decimal:2',
        'add_bentonite_ma' => 'decimal:2',
        'total_sand' => 'decimal:2',
        'add_water_bc10' => 'decimal:2',
        'lama_bc10_jalan' => 'decimal:2',
        'rating_pasir_es' => 'decimal:2',
        'bc9_ic_moist' => 'decimal:2',
        'bc9_ic_ac' => 'decimal:2',
        'ssi1_awal' => 'decimal:2',
        'ssi1_akhir' => 'decimal:2',
        'ssi2_awal' => 'decimal:2',
        'ssi2_akhir' => 'decimal:2',
    ];
}
